name: Deploy React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      # Global Mock Mode Configuration
      NEXT_PUBLIC_MOCK_MODE: true
      NEXT_PUBLIC_USE_MOCK_AAVE: true
      NEXT_PUBLIC_USE_MOCK_API: true
      NEXT_PUBLIC_USE_MOCK_CONTRACTS: true
      
      # API Configuration
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5000
      
      # Contract Addresses (mock/test addresses)
      NEXT_PUBLIC_PIV_ADDRESS: 0x1234567890123456789012345678901234567890
      NEXT_PUBLIC_ROUTER_ADDRESS: 0x2345678901234567890123456789012345678901
      
      # Network Configuration - Updated for Sepolia testnet
      NEXT_PUBLIC_CHAIN_ID: 11155111
      NEXT_PUBLIC_NETWORK_NAME: sepolia
      NEXT_PUBLIC_RPC_URL: https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build app
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build